---
resources:
- name: newman-repo
  type: git
  source:
    uri: https://github.com/mkreibe/ConcourseCI-Newman.git
  
jobs:
- name: test-rest-api
  public: true
  plan:
  - get: newman-repo
  - task: run-newman
    file: newman-repo/newman/newman-task.yml
    params: {"ENVIRONMENT_URL": "env", "COLLECTION_URL": "url"}