---
resources:
- name: 1m
  type: time
  source: {interval: 1m}

- name: newman-repo
  type: git
  source:
    uri: https://github.com/mkreibe/ConcourseCI-Newman.git
  
jobs:
- name: test-rest-api
  public: true
  plan:
  - get: 1m
    trigger: true
  - get: newman-repo
  - task: run-newman
    file: newman-repo/newman/newman-task.yml
    inputs:
    - name: newman-repo
    params: {"ENVIRONMENT_URL": "env", "COLLECTION_URL": "url"}